baseURL: "https://hanifan.netlify.app"
languageCode: "en-us"
title: "Hanifan's Profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Hanifan's Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hanifan."
    subtitle: "I build things with flutter !"
    content: "A passionate flutter developer. I tend to make use of flutter technologies to build apps that looks great, feels fantastic, and functions correctly."
    # image: /images/ava.jpgm 
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/hanifann
        - icon: fab fa-facebook
          url: https://www.facebook.com/profile.php?id=100006769218057
        - icon: fa fa-phone
          url: https://api.whatsapp.com/send/?phone=%2B62813244145108&text&type=phone_number&app_absent=0

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/face.jpg"
    content: |-
      I am a software developer with a passion for mobile app development. I have a background in computer science, and I have a strong knowledge about flutter framework. I've been developing apps using flutter for about 2 years. I am currently working as a flutter developer at [Pusat Teknologi Informasi (PuTI)](https://it.telkomuniversity.ac.id/profil-puti/) in Telkom University Bandung. 

      I am currently working on My Tel-U Mobile.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Flutter"
        - "Kotlin"
        - "Laravel"
        - "Git"
        - "Linux"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Flutter Developer"
        company: "Pusat Tekologi Informasi Telkom Univeristy"
        companyUrl: "https://it.telkomuniversity.ac.id/profil-puti/"
        date: "February 2021 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://play.google.com/store/apps/details?id=com.telu.puti.mytelu&hl=en"
        content: "I am currently working as a flutter developer at [Pusat Teknologi Informasi (PuTI)](https://it.telkomuniversity.ac.id/profil-puti/) in Telkom University Bandung. I am currently working on an app project that will help Telkom Uninversity academic community used to obtain academic information."
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Informatics Engineering"
        school:
          name: "Telkom University, Bandung, Indonesia"
        date: "2021 - now"
        GPA: "3.52 out of 4.0"
      - title: "Diploma of Informatics Engineering"
        school:
          name: "Telkom University, Bandung, Indonesia"
        date: "2018 - 2021"
        GPA: "3.56 out of 4.0"
        content: |-
          Extracurricular Activities
            - Member of Information and Security Club (Inseclub) organization. 
            - Member of Central Computer Improvement, GnG Division.
      - title: "High School"
        school:
          name: "SMA Negeri 1 jatiwangi."
        date: "2016-2018"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: 2nd Place Innovilage 2021 on Digital Social Solution
        content: We developed a product that can help monitor and tackel the spread of TB/TBC.
      - title: Silver award at Indonesia Healthcare Innovation Awards IHIA V-2021
        content: We developed an app called jantungku which used for consulting heart disease problems.

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Jantungku
        content: an application used for consulting heart disease problems. This app also won a silver award at Indonesia Healthcare Innovation Awards IHIA V-2021
        image: /images/projects/jantungku.png
        featured:
          name: Install
          link: https://play.google.com/store/apps/details?id=com.sehatutama.jantungku&hl=in&gl=US
        badges:
          - "Flutter"

      - title: TBC Counter
        content: health service application aimed at rural communities so they can tackle the spread and cure of TB/TBC.
        image: /images/projects/tbc.png
        featured:
          name: Install
          link: https://play.google.com/store/apps/details?id=com.innovilage.tbcounter
        badges:
          - "Flutter"

      - title: xedu
        content: an application for educating and reporting sexual abuse.
        image: /images/projects/xedu.png
        featured:
          name: Install
          link: https://play.google.com/store/apps/details?id=com.innovillage.xedu
        badges:
          - "Flutter"
        links:
          - icon: fab fa-github
            url: https://github.com/hanifann/xedu

      - title: My Tel-U Mobile
        content: an application that will help Telkom Uninversity academic community used to obtain academic information.
        image: /images/projects/telu.png
        featured:
          name: Install
          link: https://play.google.com/store/apps/details?id=com.telu.puti.mytelu
        badges:
          - "Flutter"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: hanifannurulhaq@outlook.com
    btnName: Mail me

  # footer:
  #   recentPosts:
  #     path: "blogs"
  #     count: 3
  #     title: Recent Posts
  #     enable: false
  #     disableFeaturedImage: false
  #   socialNetworks:
  #     github: https://github.com/hanifann
  #     linkedin: https://www.linkedin.com/in/hanifannh/
  #     facebook: https://www.facebook.com/profile.php?id=100006769218057

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false